# Generated by Django 4.1.5 on 2023-02-10 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Ain', 'Aisne'), ('Allier', 'Alpes-de-Haute-Provence'), ('Hautes-Alpes', 'Alpes-Maritimes'), ('Ardèche', 'Ardennes'), ('Ariège', 'Aube'), ('Aude', 'Aveyron'), ('Bouches-du-Rhône', 'Calvados'), ('Cantal', 'Charente'), ('Charente-Maritime', 'Cher'), ('Corrèze', 'Corse-du-Sud'), ('Haute-Corse', 'Creuse'), ('Dordogne', 'Doubs'), ('Drôme', 'Eure'), ('Finistère', 'Gard'), ('Haute-Garonne', 'Gers'), ('Gironde', 'Hérault'), ('Indre', 'Indre-et-Loire'), ('Isère', 'Jura'), ('Landes', 'Loir-et-Cher'), ('Loire', 'Haute-Loire'), ('Loire-Atlantique', 'Loiret'), ('Lot', 'Lot-et-Garonne'), ('Lozère', 'Maine-et-Loire'), ('Manche', 'Marne'), ('Haute-Marne', 'Mayenne')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
