# Generated by Django 4.1.5 on 2023-02-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Ain', 'Aisne'), ('Allier', 'Alpes-de-Haute-Provence'), ('Hautes-Alpes', 'Alpes-Maritimes'), ('Ardèche', 'Ardennes'), ('Ariège', 'Aube'), ('Aude', 'Aveyron'), ('Bouches du Rhone', 'Calvados'), ('Cantal', 'Charente'), ('Charente-Maritime', 'Cher'), ('Corrèze', 'Corse-du-Sud'), ('Haute-Corse', 'Creuse'), ('Dordogne', 'Doubs'), ('Drôme', 'Eure'), ('Finistère', 'Gard'), ('Haute-Garonne', 'Gers'), ('Gironde', 'Hérault'), ('Indre', 'Indre-et-Loire'), ('Isère', 'Jura'), ('Landes', 'Loir-et-Cher'), ('Loire', 'Haute-Loire'), ('Loire-Atlantique', 'Loiret'), ('Lot', 'Lot-et-Garonne'), ('Lozère', 'Maine-et-Loire'), ('Manche', 'Marne'), ('Haute-Marne', 'Mayenne')], max_length=100),
        ),
    ]
